### ISSUE TITLE
options flag appears to be unimplemented

### ISSUE THREAD

**Issue by jaknz** [WardsParadox/PrinterProfileGenerator#1]
Calling the script with `[--options [OPTIONS [OPTIONS ...]]]` results in an unknown flag error. Looks like this flag went out with the jankie code clean-up?

**Comment by WardsParadox** [comment]
Probably. I had some time to work on it and then school started here. As soon as it calms down a bit, I'll take a look.

**Comment by WardsParadox** [comment]
@jaknz Try now. Make sure to use seperate `--option` flags for each one.

**Comment by jaknz** [comment]
Looks happy!

**Comment by WardsParadox** [comment]
🍻
